jobs:
  - deployment: Run_E2E_Tests
    pool:
      vmImage: ubuntu-20.04
    container: mcr.microsoft.com/playwright:v1.32.0-focal
    environment: testing
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self
            - task: Bash@3
              displayName: 'Install dependencies'
              inputs:
                workingDirectory: 'tests/e2e'
                targetType: 'inline'
                failOnStderr: true
                env:
                CI: true
                script: npm install
            - task: Bash@3
              displayName: 'Install Java'
              inputs:
                targetType: 'inline'
                script: |
                  apt-get update
                  apt-get install -y default-jdk
                  export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
            - task: Bash@3
              displayName: 'Install Allure'
              inputs:
                targetType: 'inline'
                script: |
                  apt-get install sudo
                  sudo apt-get update
                  sudo apt-add-repository ppa:qameta/allure -y
                  sudo apt-get install allure -y
                  allure --version      
            - task: Bash@3
              displayName: 'Run Playwright tests'
              inputs:
                workingDirectory: 'tests/e2e'
                targetType: 'inline'
                failOnStderr: true
                env:
                CI: true
                script: npm run tests:allure 
            - task: Bash@3
              displayName: 'Generate Allure report'
              inputs:
                workingDirectory: 'allure-results'
                targetType: 'inline'
                failOnStderr: true
                env:
                CI: true
                script: npm run results:allure           
            - task: PublishTestResults@2
              displayName: 'Publish test results'
              inputs:
                searchFolder: 'junit-results/'
                testResultsFormat: 'JUnit'
                testResultsFiles: 'e2e-test-results.xml'
                mergeTestResults: true
                failTaskOnFailedTests: false
                testRunTitle: 'Sauce Demo E2E Tests'
              condition: succeededOrFailed()
            - task: PublishAllureReport@1
              displayName: 'Publish Allure Report'
              inputs:
                reportDir: 'allure-report'
            - task: CopyFiles@2
              displayName: 'Copy Allure report'
              inputs:
                SourceFolder: $(Build.Repository.LocalPath)/allure-report/
                Contents: '**'
                TargetFolder: $(Build.ArtifactStagingDirectory)/allure-report/
  
    
